### ISSUE TITLE
发现一个问题，内存占用过多的问题。

### ISSUE THREAD

**Issue by Yeyanbin** [Yeyanbin/yubi_image_manager#1]
<img width="488" alt="image" src="https://github.com/user-attachments/assets/d3e716db-e6fc-49a7-b8b9-11a93575f636">
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/de1cf770-66ea-4837-a184-3e246085ed22">

虽然这里的图片看起来是已经被压缩了缩略图，但是Flutter会把原图直接加载到内存里，所以会导致占用内存过多。

暂定解决方案：使用flutter_image_compress生成宽度和高度小于等于150的缩略图缓存到本地。

**Comment by yubi233** [comment]
在滑动到占满电脑内存的时候，就会触发内存清理，从而导致载入图片缓慢的白屏现象。
